[project]
name = "agent-communication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk>=0.3.22",
    "langchain-ollama>=1.0.1",
    "langgraph>=1.0.6",
    "pydantic>=2.12.5",
]
